### ISSUE TITLE
Setting session_timeout_ms field raises an error

### ISSUE THREAD

**Issue by gquintana** [logstash-plugins/logstash-input-kafka#114]
```
{:timestamp=>"2016-08-04T16:40:58.885000+0200", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::Kafka topics=>[\"logpic\"], bootstrap_servers=>\"kafka1:9092,kafka2:9092,kafka3:9092\", max_partition_fetch_bytes=>\"5242880\", session_timeout_ms=>\"180000\", group_id=>\"logpic\", codec=><LogStash::Codecs::JSON charset=>\"UTF-8\">, type=>\"logstash-indexer-input-pic\", tags=>[\"logstash-indexer-input-pic\"], ssl=>false, ssl_truststore_location=>\"/appli/projects/sup/supervision/logstash/keystore.jks\", ssl_truststore_password=><password>, auto_commit_interval_ms=>\"5000\", client_id=>\"logstash\", consumer_threads=>1, enable_auto_commit=>\"true\", key_deserializer_class=>\"org.apache.kafka.common.serialization.StringDeserializer\", value_deserializer_class=>\"org.apache.kafka.common.serialization.StringDeserializer\", poll_timeout_ms=>100>\n  Error: uncaught throw Failed to construct kafka consumer in thread 0x31878\n  Exception: ArgumentError\n  Stack: org/jruby/RubyKernel.java:1283:in `throw'\n/appli/projects/sup/supervision/logstash/logstash-2.3.4/vendor/local_gems/fc1d0069/logstash-input-kafka-3.0.3/lib/logstash/inputs/kafka.rb:213:in `create_consumer'\n/appli/projects/sup/supervision/logstash/logstash-2.3.4/vendor/local_gems/fc1d0069/logstash-input-kafka-3.0.3/lib/logstash/inputs/kafka.rb:210:in `create_consumer'\n/appli/projects/sup/supervision/logstash/logstash-2.3.4/vendor/local_gems/fc1d0069/logstash-input-kafka-3.0.3/lib/logstash/inputs/kafka.rb:141:in `run'\norg/jruby/RubyFixnum.java:275:in `times'\norg/jruby/RubyEnumerator.java:274:in `each'\norg/jruby/RubyEnumerable.java:757:in `map'\n/appli/projects/sup/supervision/logstash/logstash-2.3.4/vendor/local_gems/fc1d0069/logstash-input-kafka-3.0.3/lib/logstash/inputs/kafka.rb:141:in `run'\n/appli/projects/sup/supervision/logstash/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:342:in `inputworker'\n/appli/projects/sup/supervision/logstash/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:336:in `start_input'", :level=>:error, :file=>"logstash/pipeline.rb", :line=>"353", :method=>"inputworker"}
```

- Version: 3.0 (Logstash 2.3)
- Operating System: RHEL 6.4
- Config File :
```
  kafka {
    topics => ["logpic"]
    bootstrap_servers => "kafka1:9092,kafka2:9092,kafka3:9092"
    max_partition_fetch_bytes => "5242880"
    session_timeout_ms => "180000"
    group_id => "logpic"
    codec => json
    type => "logstash-indexer-input-pic"
    tags => [ "logstash-indexer-input-pic" ]
    ssl => false
    ssl_truststore_location => "/appli/projects/sup/supervision/logstash/keystore.jks"
    ssl_truststore_password => <password>
  }
```

**Comment by talevy** [comment]
Interesting, not sure why this did not occur for myself...

thanks for the report, will take a look at this soon!

**Comment by gquintana** [comment]
Is it possible to get more information on this error: why the consumer creation failed?

Is it possible to get Kafka consumers logs? There are Log4J warnings on startup, is it possible to put a log4j config file somewhere?

**Comment by talevy** [comment]
@gquintana yes, we are working on updating logging in Logstash to better support these projects. In Logstash 2.3 you can set the following environment variable.

example:
```
LS_JAVA_OPTS='-Dlog4j.configuration=file:/path/to/log4j.properties'
```

**Comment by gquintana** [comment]
This issue seems to be environment related, I can not reproduce it on my desktop computer with *same configuration*. I will dig bit deeper...

**Comment by gquintana** [comment]
It's not related to JDK release or broker (Kafka server) config.

I have enabled Log4J Config, but there is no clue:

```
`2016-08-25 11:25:30,571 INFO  [main]<kafka org.apache.kafka.clients.consumer.ConsumerConfig - ConsumerConfig values:
        ...
        session.timeout.ms = 180000
        ...

2016-08-25 11:25:30,571 DEBUG [main]<kafka org.apache.kafka.clients.consumer.KafkaConsumer - Starting the Kafka consumer
2016-08-25 11:25:30,571 DEBUG [main]<kafka org.apache.kafka.clients.consumer.KafkaConsumer - The Kafka consumer has closed.
```

**Comment by gquintana** [comment]
I added a log in `kafka.rb` and I got the complete stacktrace:

```
{:timestamp=>"2016-08-25T11:46:17.030000+0200", :level=>:error, 
:message=>"Failed to construct kafka consumer", :exception=>Java::OrgApacheKafkaCommon::KafkaException, 
:backtrace=>[
  "org.apache.kafka.clients.consumer.KafkaConsumer.<init>(org/apache/kafka/clients/consumer/KafkaConsumer.java:648)", 
  "org.apache.kafka.clients.consumer.KafkaConsumer.<init>(org/apache/kafka/clients/consumer/KafkaConsumer.java:542)", 
  "org.apache.kafka.clients.consumer.KafkaConsumer.<init>(org/apache/kafka/clients/consumer/KafkaConsumer.java:524)", 
  "java.lang.reflect.Constructor.newInstance(java/lang/reflect/Constructor.java:423)", 
  "LogStash::Inputs::Kafka.create_consumer(/appli/projects/sup/supervision/logstash/logstash-2.3.4/vendor/local_gems/9dbd8cce/logstash-input-kafka-3.0.3/lib/logstash/inputs/kafka.rb:210)",
  "LogStash::Inputs::Kafka.create_consumer(/appli/projects/sup/supervision/logstash/logstash-2.3.4/vendor/local_gems/9dbd8cce/logstash-input-kafka-3.0.3/lib/logstash/inputs/kafka.rb:210)", 
  "LogStash::Inputs::Kafka.run(/appli/projects/sup/supervision/logstash/logstash-2.3.4/vendor/local_gems/9dbd8cce/logstash-input-kafka-3.0.3/lib/logstash/inputs/kafka.rb:141)", 
  "LogStash::Inputs::Kafka.run(/appli/projects/sup/supervision/logstash/logstash-2.3.4/vendor/local_gems/9dbd8cce/logstash-input-kafka-3.0.3/lib/logstash/inputs/kafka.rb:141)", 
  "org.jruby.RubyFixnum.times(org/jruby/RubyFixnum.java:275)", 
  "org.jruby.RubyEnumerator.each(org/jruby/RubyEnumerator.java:274)", 
  "org.jruby.RubyEnumerable.map(org/jruby/RubyEnumerable.java:757)", 
  "LogStash::Inputs::Kafka.run(/appli/projects/sup/supervision/logstash/logstash-2.3.4/vendor/local_gems/9dbd8cce/logstash-input-kafka-3.0.3/lib/logstash/inputs/kafka.rb:141)", 
  "LogStash::Inputs::Kafka.run(/appli/projects/sup/supervision/logstash/logstash-2.3.4/vendor/local_gems/9dbd8cce/logstash-input-kafka-3.0.3/lib/logstash/inputs/kafka.rb:141)", 
  "RUBY.inputworker(/appli/projects/sup/supervision/logstash/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:342)", 
  "RUBY.start_input(/appli/projects/sup/supervision/logstash/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:336)", 
  "java.lang.Thread.run(java/lang/Thread.java:745)"]}

**Comment by gquintana** [comment]
In my Log4J, I have several warnings, even when I don't set `session_timeout_ms`:

```
2016-08-25 09:12:01 WARN  AppInfoParser - Error registering AppInfo mbean
javax.management.InstanceAlreadyExistsException: kafka.consumer:type=app-info,id=logstash
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:57)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:640)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:542)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:524)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
```

I think it's unrelated but I may be wrong.

**Comment by gquintana** [comment]
The KafkaException wraps a ConfigException

```
org.apache.kafka.common.config.ConfigException: request.timeout.ms should be greater than session.timeout.ms and fetch.max.wait.ms
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:557)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:542)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:524)
        at sun.reflect.GeneratedConstructorAccessor28.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.jruby.javasupport.JavaConstructor.newInstanceDirect(JavaConstructor.java:277)
```
`request.timeout.ms` is set to 40000 by default. Setting `request_timeout_ms` to `session_timeout_ms`+10s solves the issue.

In the end to fix this issue, one could:
- Write in the documentation that session_timeout_ms < request_timeout_ms and that request_timeout_ms is set too 40000 by default
- Improve error message by dumping the whole Java stack trace (I don't know how to do that with JRuby)
