### ISSUE TITLE
integration test failure: "Kafka Input can ingest 37 apache log lines from Kafka broker"

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-input-kafka#137]
one of kafka's integration test is occasionally breaking the master or 5.x branches

see more on: https://travis-ci.org/elastic/logstash/builds/167292361

```
Failures:

  1) Kafka Input can ingest 37 apache log lines from Kafka broker
     Failure/Error: wait(timeout_seconds).for { @fixture.output_exists? }.to be true

       expected true
            got false
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:13:in `handle_matcher'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:10:in `handle_matcher'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:9:in `handle_matcher'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:30:in `to'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:44:in `with_wait'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:28:in `with_wait'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:44:in `with_wait'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:30:in `to'
     # ./specs/kafka_input_spec.rb:20:in `(root)'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
```

@talevy pinging you as you're more familiar with the plugin

**Comment by talevy** [comment]
I'll take a look, thanks

**Comment by talevy** [comment]
assigned @suyograo since he said he is taking a look

**Comment by suyograo** [comment]
Closing since its no longer an issue
