### ISSUE TITLE
logstash5.1.7 input kafka

### ISSUE THREAD

**Issue by huangkunqua** [logstash-plugins/logstash-input-kafka#217]
[2017-08-01T14:22:05,319][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NameError: undefined local variable or method `dotfile' for #<AwesomePrint::Inspector:0x89e35a4>>, :backtrace=>["/usr/local/logstash-5.4.3/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:163:in `merge_custom_defaults!'", "/usr/local/logstash-5.4.3/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:50:in `initialize'", "/usr/local/logstash-5.4.3/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/core_ext/kernel.rb:9:in `ai'", "/usr/local/logstash-5.4.3/vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-3.0.2/lib/logstash/codecs/rubydebug.rb:39:in `encode_default'", "org/jruby/RubyMethod.java:120:in `call'", "/usr/local/logstash-5.4.3/vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-3.0.2/lib/logstash/codecs/rubydebug.rb:35:in `encode'", "/usr/local/logstash-5.4.3/logstash-core/lib/logstash/codecs/base.rb:50:in `multi_encode'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/local/logstash-5.4.3/logstash-core/lib/logstash/codecs/base.rb:50:in `multi_encode'", "/usr/local/logstash-5.4.3/logstash-core/lib/logstash/outputs/base.rb:90:in `multi_receive'", "/usr/local/logstash-5.4.3/logstash-core/lib/logstash/output_delegator_strategies/single.rb:15:in `multi_receive'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/usr/local/logstash-5.4.3/logstash-core/lib/logstash/output_delegator_strategies/single.rb:14:in `multi_receive'", "/usr/local/logstash-5.4.3/logstash-core/lib/logstash/output_delegator.rb:47:in `multi_receive'", "/usr/local/logstash-5.4.3/logstash-core/lib/logstash/pipeline.rb:407:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/local/logstash-5.4.3/logstash-core/lib/logstash/pipeline.rb:406:in `output_batch'", "/usr/local/logstash-5.4.3/logstash-core/lib/logstash/pipeline.rb:352:in `worker_loop'", "/usr/local/logstash-5.4.3/logstash-core/lib/logstash/pipeline.rb:317:in `start_workers'"]}

**Comment by huangkunqua** [comment]
kafka {
       bootstrap_servers => "localhost:9092"
       topics => "mylog_topic"
       group_id => "12"
       consumer_threads =>1
       decorate_events => true
      key_deserializer_class => "org.apache.kafka.common.serialization.ByteArrayDeserializer"
      value_deserializer_class => "org.apache.kafka.common.serialization.StringDeserializer"


 }

**Comment by huangkunqua** [comment]
why error?
