### ISSUE TITLE
Logstash initialization warning

### ISSUE THREAD

**Issue by oazabir** [logstash-plugins/logstash-input-kafka#60]
When I start logstash, I get the following warning:

         [2016-01-04T08:22:54.930]  WARN: kafka.client.ClientUtils$: Fetching topic metadata with correlation id 144 for topics [Set(rsyslog_logstash)] from broker [id:3,host:rdl04910app05,port:9092] failed
        java.nio.channels.ClosedChannelException
                at kafka.network.BlockingChannel.send(BlockingChannel.scala:100)
                at kafka.producer.SyncProducer.liftedTree1$1(SyncProducer.scala:73)
                at kafka.producer.SyncProducer.kafka$producer$SyncProducer$$doSend(SyncProducer.scala:72)
                at kafka.producer.SyncProducer.send(SyncProducer.scala:113)
                at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:58)
                at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:93)
                at kafka.consumer.ConsumerFetcherManager$LeaderFinderThread.doWork(ConsumerFetcherManager.scala:66)
                at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:60)
        log4j, [2016-01-04T08:22:55.184]  WARN: kafka.client.ClientUtils$: Fetching topic metadata with correlation id 145 for topics [Set(rsyslog_logstash)] from broker [id:3,host:rdl04910app05,port:9092] failed
        java.nio.channels.ClosedChannelException
                at kafka.network.BlockingChannel.send(BlockingChannel.scala:100)
                at kafka.producer.SyncProducer.liftedTree1$1(SyncProducer.scala:73)
                at kafka.producer.SyncProducer.kafka$producer$SyncProducer$$doSend(SyncProducer.scala:72)
                at kafka.producer.SyncProducer.send(SyncProducer.scala:113)
                at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:58)
                at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:93)
                at kafka.consumer.ConsumerFetcherManager$LeaderFinderThread.doWork(ConsumerFetcherManager.scala:66)
                at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:60)

There's no message in the topic. Logstash isn't really doing anything.

**Comment by joekiller** [comment]
These are warnings from #61 it seems like your zk might've been hosed causing these other warnings.

**Comment by joekiller** [comment]
I don't think this or #61 are really plugin issues.  Please reopen if you think otherwise.
