### ISSUE TITLE
Continuous exception when kafka servers are restarted

### ISSUE THREAD

**Issue by oazabir** [logstash-plugins/logstash-input-kafka#61]
When I stopped and started all kafka & zookeeper servers, I started receiving continuous exception from logstash. 

[2016-01-04T08:50:07.425]  WARN: kafka.consumer.ConsumerFetcherManager$LeaderFinderThread: [logstash_rdl04910app06-1451895739775-36bdd0f3-leader-finder-thread], Failed to find leader for Set([rsyslog_logstash,0], [rsyslog_logstash,2], [rsyslog_logstash,1])
        kafka.common.KafkaException: fetching topic metadata for topics [Set(rsyslog_logstash)] from broker [ArrayBuffer()] failed
                at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:72)
                at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:93)
                at kafka.consumer.ConsumerFetcherManager$LeaderFinderThread.doWork(ConsumerFetcherManager.scala:66)
                at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:60)
        log4j, [2016-01-04T08:50:07.628]  WARN: kafka.consumer.ConsumerFetcherManager$LeaderFinderThread: [logstash_rdl04910app06-1451895739775-36bdd0f3-leader-finder-thread], Failed to find leader for Set([rsyslog_logstash,0], [rsyslog_logstash,2], [rsyslog_logstash,1])
        kafka.common.KafkaException: fetching topic metadata for topics [Set(rsyslog_logstash)] from broker [ArrayBuffer()] failed
                at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:72)
                at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:93)
                at kafka.consumer.ConsumerFetcherManager$LeaderFinderThread.doWork(ConsumerFetcherManager.scala:66)
                at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:60)
        log4j, [2016-01-04T08:50:07.832]  WARN: kafka.consumer.ConsumerFetcherManager$LeaderFinderThread: [logstash_rdl04910app06-1451895739775-36bdd0f3-leader-finder-thread], Failed to find leader for Set([rsyslog_logstash,0], [rsyslog_logstash,2], [rsyslog_logstash,1])
        kafka.common.KafkaException: fetching topic metadata for topics [Set(rsyslog_logstash)] from broker [ArrayBuffer()] failed
                at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:72)
                at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:93)
                at kafka.consumer.ConsumerFetcherManager$LeaderFinderThread.doWork(ConsumerFetcherManager.scala:66)
                at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:60)
        log4j, [2016-01-04T08:50:08.035]  WARN: kafka.consumer.ConsumerFetcherManager$LeaderFinderThread: [logstash_rdl04910app06-1451895739775-36bdd0f3-leader-finder-thread], Failed to find leader for Set([rsyslog_logstash,0], [rsyslog_logstash,2], [rsyslog_logstash,1])
        kafka.common.KafkaException: fetching topic metadata for topics [Set(rsyslog_logstash)] from broker [ArrayBuffer()] failed
                at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:72)
                at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:93)
                at kafka.consumer.ConsumerFetcherManager$LeaderFinderThread.doWork(ConsumerFetcherManager.scala:66)
                at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:60)

I had to kill the instance. 

On the zookeeper log as well, I was seeing continuous exceptions:

        [2016-01-04 08:52:11,652] WARN Ignoring exception (org.apache.zookeeper.server.NIOServerCnxnFactory)
        java.io.IOException: Too many open files
                at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
                at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
                at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:188)
                at java.lang.Thread.run(Thread.java:745)
        [2016-01-04 08:52:11,653] WARN Ignoring exception (org.apache.zookeeper.server.NIOServerCnxnFactory)
        java.io.IOException: Too many open files
                at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
                at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
                at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:188)
                at java.lang.Thread.run(Thread.java:745)
        [2016-01-04 08:52:11,653] WARN Ignoring exception (org.apache.zookeeper.server.NIOServerCnxnFactory)
        java.io.IOException: Too many open files
                at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
                at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
                at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:188)
                at java.lang.Thread.run(Thread.java:745)
        [2016-01-04 08:52:11,653] WARN Ignoring exception (org.apache.zookeeper.server.NIOServerCnxnFactory)
        java.io.IOException: Too many open files
                at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
                at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
                at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:188)
                at java.lang.Thread.run(Thread.java:745)

**Comment by joekiller** [comment]
Seems like zk didn't have enough file handles and that caused a cascading error. https://www.google.com/search?q=zookeeper+too+many+open+files+kafka&oq=zookeeper+too+many+open+files+kafka
